### PR TITLE
Fix conversion of unknown or null collections to empty in nested objects

### PR DESCRIPTION
**Pull request by paaanic**
This PR fixes the problem mentioned in https://github.com/hashicorp/terraform-plugin-codegen-framework/issues/160.

Thanks to @austinvalle for the code snippet that was left in the issue as an example and used as a basis for this fix.

### CODE REVIEW

**Review by austinvalle — COMMENTED** [review]
Thanks for the contribution @paaanic, everything here make sense, although we don't have a ton of robust acceptance tests outside of the snapshot-like tests we have. I think generally this should cover the original bug report, although I wouldn't be surprised if other custom type implementations have similar null/unknown handling issues.

Would you mind also creating a bugfix changelog for this PR? (this repo doesn't have a contributing document I'm seeing, but you can [reference the plugin-framework one](https://github.com/hashicorp/terraform-plugin-framework/blob/main/.github/CONTRIBUTING.md#changelog))

**Comment by paaanic** [comment]
Thank you for the quick review @austinvalle. Added a changelog entry.

**Comment by paaanic** [comment]
It is worth noting that the same problem is mentioned in the #154, so this PR should fix it as well.

**Review by austinvalle — APPROVED** [review]
LGTM, thanks for the fix!

I'll release this in `v0.4.1` 🚀

**Pull request merged**
