### PR TITLE
Fix package name when not set as a CLI flag

### PR DESCRIPTION
**Pull request by remilapeyre**

### CODE REVIEW

**Review by bendbennett — COMMENTED** [review]
Hi @remilapeyre 👋 

Thank you for your contribution.

Is the primary purpose for this PR to introduce another variable so that the method argument, `packageName`, is not mutated?

**Comment by remilapeyre** [comment]
> Hi @remilapeyre 👋
> 
> Thank you for your contribution.
> 
> Is the primary purpose for this PR to introduce another variable so that the method argument, `packageName`, is not mutated?

Hi, sorry I should have explained. Yes the idea is to not mutate `packageName` because after the first pass in the loop it was already set so all package had the same name because the condition `if packageName == ""` was always false after the first iteration.

With this change all packages have the appropriate name when the flag `--package` is not set in the command line.

**Review by bendbennett — APPROVED** [review]
LGTM 🚀

**Comment by bendbennett** [comment]
> > Hi @remilapeyre 👋
> > Thank you for your contribution.
> > Is the primary purpose for this PR to introduce another variable so that the method argument, `packageName`, is not mutated?
> 
> Hi, sorry I should have explained. Yes the idea is to not mutate `packageName` because after the first pass in the loop it was already set so all package had the same name because the condition `if packageName == ""` was always false after the first iteration.
> 
> With this change all packages have the appropriate name when the flag `--package` is not set in the command line.

Thanks! I'd skimmed right over that. Many thanks for the fix.

**Pull request merged**
